command_timeout = 1000

[aws]
format = ""

[directory]
truncate_to_repo = true
truncation_length = -1
style = "fg:bright-green"

[username]
show_always = false
style_root = "bold fg:bright-blue"
style_user = "bold fg:bright-blue"

[git_branch]
format = "[$symbol$branch]($style) "
style = "fg:bright-yellow"

[line_break]
disabled = false

[time]
disabled = true
format = 'ğŸ•™[ $time ]($style)'
time_format = "%R"

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡¡${ahead_count} â‡£${behind_count}"
behind = "â‡£${count}"
conflicted = "[ğŸ¤ª ${count}](bright-red) "
untracked = "ğŸ¤· â€${count} "
stashed = "[ğŸ“¦ ${count}](bright-blue) "
modified = "[ğŸ“’ ${count}](yellow) "
staged = "[âœ” ${count}](green) "
renamed = "[ğŸš— ${count}](bright-red) "
deleted = "[ğŸ—‘ ${count}](red) "

[git_commit]
only_detached = true

[java]
disabled = true

[package]
disabled = true
